### ISSUE TITLE
Can't build on Zorin OS (Ubuntu 20.04)

### ISSUE THREAD

**Issue by hfc2x** [gort818/qtwebflix#89]
Hey, I just wanted to thank you for this amazing app, because it's the solution to watching Netflix on Linux.

I have encountered an issue trying to build this on Zorin OS, which is based off of Ubuntu 20.04 LTS. Tested this out with vanilla Ubuntu 20.04 as well, and the same thing happens.

Most of the distros I tried this with work flawlessly, and by this I mean most of the popular Ubuntu-based distros, as well as Arch-based ones. For the Ubuntu-based ones (that are usually based on 22.04 LTS) I've managed to get it working with no issues with these steps:

1. Install the following dependencies: `build-essential`, `git`, `qtchooser`, `qt5-qmake` and `qtwebengine5-dev`
2. Clone the repository with `git clone --recursive https://github.com/gort818/qtwebflix.git`
3. Install widevine libs with `chmod +x ./widevine.sh && sudo ./widevine.sh`
4. Compile with `qmake -config release && make`

The output I get on Zorin OS 16.2, as well as Ubuntu 20.04, by doing the exact same, is the following:

```
mainwindow.cpp: In member function ‘void MainWindow::parseCommand()’:
mainwindow.cpp:360:38: error: ‘class QWebEngineProfile’ has no member named ‘setUrlRequestInterceptor’; did you mean ‘setRequestInterceptor’?
  360 |    this->webview->page()->profile()->setUrlRequestInterceptor(
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                      setRequestInterceptor
make[1]: *** [Makefile:557: mainwindow.o] Error 1
make[1]: Leaving directory '/home/hugazo/build/qtwebflix/src'
make: *** [Makefile:136: sub-src-make_first-ordered] Error 2
```

This seems to be because the `qtwebengine5-dev` package is outdated in that particular Ubuntu version. What to do in this situation?
